server:
  port: 8080

spring:
  #    mvc:
  #      view:
  #        prefix: /
  #        suffix: .html
    datasource:
        name: Ma
        url: jdbc:mysql://localhost:3306/ZHJXUAT?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
        username: root
        password: Root-123
        driver-class-name: com.mysql.cj.jdbc.Driver
