server:
  port: 8080
  servlet:
    context-path: /wechat-zhjx

spring:
    datasource:
        name: Ma
        url: jdbc:mysql://localhost:3306/springbootTest?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
        username: root
        password: Root-123
        driver-class-name: com.mysql.cj.jdbc.Driver
