package com.example.springbootdemo.pojo;

import java.util.Date;

public class CarCardDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_card_detail.region
     *
     * @mbg.generated
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_card_detail.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_card_detail.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_card_detail.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_card_detail.yuy_type
     *
     * @mbg.generated
     */
    private String yuyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_card_detail.card_no
     *
     * @mbg.generated
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_card_detail.on_card_time
     *
     * @mbg.generated
     */
    private Date onCardTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_card_detail.wechat_id
     *
     * @mbg.generated
     */
    private String wechatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_card_detail.yuy_username
     *
     * @mbg.generated
     */
    private String yuyUsername;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_card_detail.region
     *
     * @return the value of car_card_detail.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_card_detail.region
     *
     * @param region the value for car_card_detail.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_card_detail.province
     *
     * @return the value of car_card_detail.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_card_detail.province
     *
     * @param province the value for car_card_detail.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_card_detail.city
     *
     * @return the value of car_card_detail.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_card_detail.city
     *
     * @param city the value for car_card_detail.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_card_detail.create_time
     *
     * @return the value of car_card_detail.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_card_detail.create_time
     *
     * @param createTime the value for car_card_detail.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_card_detail.yuy_type
     *
     * @return the value of car_card_detail.yuy_type
     *
     * @mbg.generated
     */
    public String getYuyType() {
        return yuyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_card_detail.yuy_type
     *
     * @param yuyType the value for car_card_detail.yuy_type
     *
     * @mbg.generated
     */
    public void setYuyType(String yuyType) {
        this.yuyType = yuyType == null ? null : yuyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_card_detail.card_no
     *
     * @return the value of car_card_detail.card_no
     *
     * @mbg.generated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_card_detail.card_no
     *
     * @param cardNo the value for car_card_detail.card_no
     *
     * @mbg.generated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_card_detail.on_card_time
     *
     * @return the value of car_card_detail.on_card_time
     *
     * @mbg.generated
     */
    public Date getOnCardTime() {
        return onCardTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_card_detail.on_card_time
     *
     * @param onCardTime the value for car_card_detail.on_card_time
     *
     * @mbg.generated
     */
    public void setOnCardTime(Date onCardTime) {
        this.onCardTime = onCardTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_card_detail.wechat_id
     *
     * @return the value of car_card_detail.wechat_id
     *
     * @mbg.generated
     */
    public String getWechatId() {
        return wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_card_detail.wechat_id
     *
     * @param wechatId the value for car_card_detail.wechat_id
     *
     * @mbg.generated
     */
    public void setWechatId(String wechatId) {
        this.wechatId = wechatId == null ? null : wechatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_card_detail.yuy_username
     *
     * @return the value of car_card_detail.yuy_username
     *
     * @mbg.generated
     */
    public String getYuyUsername() {
        return yuyUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_card_detail.yuy_username
     *
     * @param yuyUsername the value for car_card_detail.yuy_username
     *
     * @mbg.generated
     */
    public void setYuyUsername(String yuyUsername) {
        this.yuyUsername = yuyUsername == null ? null : yuyUsername.trim();
    }
}