package com.example.springbootdemo.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class CarMessDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.wechat_id
     *
     * @mbg.generated
     */
    private String wechatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.cjr_name
     *
     * @mbg.generated
     */
    private String cjrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.six
     *
     * @mbg.generated
     */
    private Integer six;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.cert_no
     *
     * @mbg.generated
     */
    private String certNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.gyr_name
     *
     * @mbg.generated
     */
    private String gyrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.gyr_phone
     *
     * @mbg.generated
     */
    private String gyrPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.gyr_certNo
     *
     * @mbg.generated
     */
    private String gyrCertno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.gyr_address
     *
     * @mbg.generated
     */
    private String gyrAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.xcz_no
     *
     * @mbg.generated
     */
    private String xczNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.jx_brand
     *
     * @mbg.generated
     */
    private String jxBrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.jx_type
     *
     * @mbg.generated
     */
    private String jxType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.jx_xh
     *
     * @mbg.generated
     */
    private String jxXh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.zhiz_changshang
     *
     * @mbg.generated
     */
    private String zhizChangshang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.fdj_glv
     *
     * @mbg.generated
     */
    private String fdjGlv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.chuc_no
     *
     * @mbg.generated
     */
    private String chucNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.guoc_or_jink
     *
     * @mbg.generated
     */
    private String guocOrJink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.fdj_pail
     *
     * @mbg.generated
     */
    private String fdjPail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.fdj_xingh
     *
     * @mbg.generated
     */
    private String fdjXingh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.chand_rongl
     *
     * @mbg.generated
     */
    private String chandRongl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.user_nianx
     *
     * @mbg.generated
     */
    private String userNianx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.fdj_no
     *
     * @mbg.generated
     */
    private String fdjNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.chuc_date
     *
     * @mbg.generated
     */
    private Date chucDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.jiq_color
     *
     * @mbg.generated
     */
    private String jiqColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.jiq_zhil
     *
     * @mbg.generated
     */
    private String jiqZhil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.goumai_date
     *
     * @mbg.generated
     */
    private Date goumaiDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.money
     *
     * @mbg.generated
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.xingz_fs
     *
     * @mbg.generated
     */
    private String xingzFs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.ranyou_type
     *
     * @mbg.generated
     */
    private String ranyouType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.waixing_chicun
     *
     * @mbg.generated
     */
    private String waixingChicun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.cheliang_sb_code
     *
     * @mbg.generated
     */
    private String cheliangSbCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.bussins_user_type
     *
     * @mbg.generated
     */
    private String bussinsUserType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.user_mess_name
     *
     * @mbg.generated
     */
    private String userMessName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.user_mess_certNo
     *
     * @mbg.generated
     */
    private String userMessCertno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.hyjs_ser_zgz
     *
     * @mbg.generated
     */
    private Integer hyjsSerZgz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.zhengshu_code
     *
     * @mbg.generated
     */
    private String zhengshuCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.shifou_jnshebao
     *
     * @mbg.generated
     */
    private Integer shifouJnshebao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.shifou_jnsheb
     *
     * @mbg.generated
     */
    private Integer shifouJnsheb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.shifou_czh
     *
     * @mbg.generated
     */
    private Integer shifouCzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_mess_detail.card_no
     *
     * @mbg.generated
     */
    private String cardNo;

    private String aduitType;
    private String onCardType;
    private String yuyType;
    private String yuyCard;

    public void setAduitType(String aduitType) {
        this.aduitType = aduitType;
    }

    public void setOnCardType(String onCardType) {
        this.onCardType = onCardType;
    }

    public void setYuyType(String yuyType) {
        this.yuyType = yuyType;
    }

    public void setYuyCard(String yuyCard) {
        this.yuyCard = yuyCard;
    }

    public String getAduitType() {
        return aduitType;
    }

    public String getOnCardType() {
        return onCardType;
    }

    public String getYuyType() {
        return yuyType;
    }

    public String getYuyCard() {
        return yuyCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.id
     *
     * @return the value of car_mess_detail.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.id
     *
     * @param id the value for car_mess_detail.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.user_name
     *
     * @return the value of car_mess_detail.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.user_name
     *
     * @param userName the value for car_mess_detail.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.wechat_id
     *
     * @return the value of car_mess_detail.wechat_id
     *
     * @mbg.generated
     */
    public String getWechatId() {
        return wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.wechat_id
     *
     * @param wechatId the value for car_mess_detail.wechat_id
     *
     * @mbg.generated
     */
    public void setWechatId(String wechatId) {
        this.wechatId = wechatId == null ? null : wechatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.create_time
     *
     * @return the value of car_mess_detail.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.create_time
     *
     * @param createTime the value for car_mess_detail.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.cjr_name
     *
     * @return the value of car_mess_detail.cjr_name
     *
     * @mbg.generated
     */
    public String getCjrName() {
        return cjrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.cjr_name
     *
     * @param cjrName the value for car_mess_detail.cjr_name
     *
     * @mbg.generated
     */
    public void setCjrName(String cjrName) {
        this.cjrName = cjrName == null ? null : cjrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.six
     *
     * @return the value of car_mess_detail.six
     *
     * @mbg.generated
     */
    public Integer getSix() {
        return six;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.six
     *
     * @param six the value for car_mess_detail.six
     *
     * @mbg.generated
     */
    public void setSix(Integer six) {
        this.six = six;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.age
     *
     * @return the value of car_mess_detail.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.age
     *
     * @param age the value for car_mess_detail.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.cert_no
     *
     * @return the value of car_mess_detail.cert_no
     *
     * @mbg.generated
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.cert_no
     *
     * @param certNo the value for car_mess_detail.cert_no
     *
     * @mbg.generated
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo == null ? null : certNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.phone
     *
     * @return the value of car_mess_detail.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.phone
     *
     * @param phone the value for car_mess_detail.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.address
     *
     * @return the value of car_mess_detail.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.address
     *
     * @param address the value for car_mess_detail.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.gyr_name
     *
     * @return the value of car_mess_detail.gyr_name
     *
     * @mbg.generated
     */
    public String getGyrName() {
        return gyrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.gyr_name
     *
     * @param gyrName the value for car_mess_detail.gyr_name
     *
     * @mbg.generated
     */
    public void setGyrName(String gyrName) {
        this.gyrName = gyrName == null ? null : gyrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.gyr_phone
     *
     * @return the value of car_mess_detail.gyr_phone
     *
     * @mbg.generated
     */
    public String getGyrPhone() {
        return gyrPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.gyr_phone
     *
     * @param gyrPhone the value for car_mess_detail.gyr_phone
     *
     * @mbg.generated
     */
    public void setGyrPhone(String gyrPhone) {
        this.gyrPhone = gyrPhone == null ? null : gyrPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.gyr_certNo
     *
     * @return the value of car_mess_detail.gyr_certNo
     *
     * @mbg.generated
     */
    public String getGyrCertno() {
        return gyrCertno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.gyr_certNo
     *
     * @param gyrCertno the value for car_mess_detail.gyr_certNo
     *
     * @mbg.generated
     */
    public void setGyrCertno(String gyrCertno) {
        this.gyrCertno = gyrCertno == null ? null : gyrCertno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.gyr_address
     *
     * @return the value of car_mess_detail.gyr_address
     *
     * @mbg.generated
     */
    public String getGyrAddress() {
        return gyrAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.gyr_address
     *
     * @param gyrAddress the value for car_mess_detail.gyr_address
     *
     * @mbg.generated
     */
    public void setGyrAddress(String gyrAddress) {
        this.gyrAddress = gyrAddress == null ? null : gyrAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.xcz_no
     *
     * @return the value of car_mess_detail.xcz_no
     *
     * @mbg.generated
     */
    public String getXczNo() {
        return xczNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.xcz_no
     *
     * @param xczNo the value for car_mess_detail.xcz_no
     *
     * @mbg.generated
     */
    public void setXczNo(String xczNo) {
        this.xczNo = xczNo == null ? null : xczNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.jx_brand
     *
     * @return the value of car_mess_detail.jx_brand
     *
     * @mbg.generated
     */
    public String getJxBrand() {
        return jxBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.jx_brand
     *
     * @param jxBrand the value for car_mess_detail.jx_brand
     *
     * @mbg.generated
     */
    public void setJxBrand(String jxBrand) {
        this.jxBrand = jxBrand == null ? null : jxBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.jx_type
     *
     * @return the value of car_mess_detail.jx_type
     *
     * @mbg.generated
     */
    public String getJxType() {
        return jxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.jx_type
     *
     * @param jxType the value for car_mess_detail.jx_type
     *
     * @mbg.generated
     */
    public void setJxType(String jxType) {
        this.jxType = jxType == null ? null : jxType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.jx_xh
     *
     * @return the value of car_mess_detail.jx_xh
     *
     * @mbg.generated
     */
    public String getJxXh() {
        return jxXh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.jx_xh
     *
     * @param jxXh the value for car_mess_detail.jx_xh
     *
     * @mbg.generated
     */
    public void setJxXh(String jxXh) {
        this.jxXh = jxXh == null ? null : jxXh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.zhiz_changshang
     *
     * @return the value of car_mess_detail.zhiz_changshang
     *
     * @mbg.generated
     */
    public String getZhizChangshang() {
        return zhizChangshang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.zhiz_changshang
     *
     * @param zhizChangshang the value for car_mess_detail.zhiz_changshang
     *
     * @mbg.generated
     */
    public void setZhizChangshang(String zhizChangshang) {
        this.zhizChangshang = zhizChangshang == null ? null : zhizChangshang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.fdj_glv
     *
     * @return the value of car_mess_detail.fdj_glv
     *
     * @mbg.generated
     */
    public String getFdjGlv() {
        return fdjGlv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.fdj_glv
     *
     * @param fdjGlv the value for car_mess_detail.fdj_glv
     *
     * @mbg.generated
     */
    public void setFdjGlv(String fdjGlv) {
        this.fdjGlv = fdjGlv == null ? null : fdjGlv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.chuc_no
     *
     * @return the value of car_mess_detail.chuc_no
     *
     * @mbg.generated
     */
    public String getChucNo() {
        return chucNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.chuc_no
     *
     * @param chucNo the value for car_mess_detail.chuc_no
     *
     * @mbg.generated
     */
    public void setChucNo(String chucNo) {
        this.chucNo = chucNo == null ? null : chucNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.guoc_or_jink
     *
     * @return the value of car_mess_detail.guoc_or_jink
     *
     * @mbg.generated
     */
    public String getGuocOrJink() {
        return guocOrJink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.guoc_or_jink
     *
     * @param guocOrJink the value for car_mess_detail.guoc_or_jink
     *
     * @mbg.generated
     */
    public void setGuocOrJink(String guocOrJink) {
        this.guocOrJink = guocOrJink == null ? null : guocOrJink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.fdj_pail
     *
     * @return the value of car_mess_detail.fdj_pail
     *
     * @mbg.generated
     */
    public String getFdjPail() {
        return fdjPail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.fdj_pail
     *
     * @param fdjPail the value for car_mess_detail.fdj_pail
     *
     * @mbg.generated
     */
    public void setFdjPail(String fdjPail) {
        this.fdjPail = fdjPail == null ? null : fdjPail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.fdj_xingh
     *
     * @return the value of car_mess_detail.fdj_xingh
     *
     * @mbg.generated
     */
    public String getFdjXingh() {
        return fdjXingh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.fdj_xingh
     *
     * @param fdjXingh the value for car_mess_detail.fdj_xingh
     *
     * @mbg.generated
     */
    public void setFdjXingh(String fdjXingh) {
        this.fdjXingh = fdjXingh == null ? null : fdjXingh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.chand_rongl
     *
     * @return the value of car_mess_detail.chand_rongl
     *
     * @mbg.generated
     */
    public String getChandRongl() {
        return chandRongl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.chand_rongl
     *
     * @param chandRongl the value for car_mess_detail.chand_rongl
     *
     * @mbg.generated
     */
    public void setChandRongl(String chandRongl) {
        this.chandRongl = chandRongl == null ? null : chandRongl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.user_nianx
     *
     * @return the value of car_mess_detail.user_nianx
     *
     * @mbg.generated
     */
    public String getUserNianx() {
        return userNianx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.user_nianx
     *
     * @param userNianx the value for car_mess_detail.user_nianx
     *
     * @mbg.generated
     */
    public void setUserNianx(String userNianx) {
        this.userNianx = userNianx == null ? null : userNianx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.fdj_no
     *
     * @return the value of car_mess_detail.fdj_no
     *
     * @mbg.generated
     */
    public String getFdjNo() {
        return fdjNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.fdj_no
     *
     * @param fdjNo the value for car_mess_detail.fdj_no
     *
     * @mbg.generated
     */
    public void setFdjNo(String fdjNo) {
        this.fdjNo = fdjNo == null ? null : fdjNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.chuc_date
     *
     * @return the value of car_mess_detail.chuc_date
     *
     * @mbg.generated
     */
    public Date getChucDate() {
        return chucDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.chuc_date
     *
     * @param chucDate the value for car_mess_detail.chuc_date
     *
     * @mbg.generated
     */
    public void setChucDate(Date chucDate) {
        this.chucDate = chucDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.jiq_color
     *
     * @return the value of car_mess_detail.jiq_color
     *
     * @mbg.generated
     */
    public String getJiqColor() {
        return jiqColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.jiq_color
     *
     * @param jiqColor the value for car_mess_detail.jiq_color
     *
     * @mbg.generated
     */
    public void setJiqColor(String jiqColor) {
        this.jiqColor = jiqColor == null ? null : jiqColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.jiq_zhil
     *
     * @return the value of car_mess_detail.jiq_zhil
     *
     * @mbg.generated
     */
    public String getJiqZhil() {
        return jiqZhil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.jiq_zhil
     *
     * @param jiqZhil the value for car_mess_detail.jiq_zhil
     *
     * @mbg.generated
     */
    public void setJiqZhil(String jiqZhil) {
        this.jiqZhil = jiqZhil == null ? null : jiqZhil.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.goumai_date
     *
     * @return the value of car_mess_detail.goumai_date
     *
     * @mbg.generated
     */
    public Date getGoumaiDate() {
        return goumaiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.goumai_date
     *
     * @param goumaiDate the value for car_mess_detail.goumai_date
     *
     * @mbg.generated
     */
    public void setGoumaiDate(Date goumaiDate) {
        this.goumaiDate = goumaiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.money
     *
     * @return the value of car_mess_detail.money
     *
     * @mbg.generated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.money
     *
     * @param money the value for car_mess_detail.money
     *
     * @mbg.generated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.xingz_fs
     *
     * @return the value of car_mess_detail.xingz_fs
     *
     * @mbg.generated
     */
    public String getXingzFs() {
        return xingzFs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.xingz_fs
     *
     * @param xingzFs the value for car_mess_detail.xingz_fs
     *
     * @mbg.generated
     */
    public void setXingzFs(String xingzFs) {
        this.xingzFs = xingzFs == null ? null : xingzFs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.ranyou_type
     *
     * @return the value of car_mess_detail.ranyou_type
     *
     * @mbg.generated
     */
    public String getRanyouType() {
        return ranyouType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.ranyou_type
     *
     * @param ranyouType the value for car_mess_detail.ranyou_type
     *
     * @mbg.generated
     */
    public void setRanyouType(String ranyouType) {
        this.ranyouType = ranyouType == null ? null : ranyouType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.waixing_chicun
     *
     * @return the value of car_mess_detail.waixing_chicun
     *
     * @mbg.generated
     */
    public String getWaixingChicun() {
        return waixingChicun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.waixing_chicun
     *
     * @param waixingChicun the value for car_mess_detail.waixing_chicun
     *
     * @mbg.generated
     */
    public void setWaixingChicun(String waixingChicun) {
        this.waixingChicun = waixingChicun == null ? null : waixingChicun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.cheliang_sb_code
     *
     * @return the value of car_mess_detail.cheliang_sb_code
     *
     * @mbg.generated
     */
    public String getCheliangSbCode() {
        return cheliangSbCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.cheliang_sb_code
     *
     * @param cheliangSbCode the value for car_mess_detail.cheliang_sb_code
     *
     * @mbg.generated
     */
    public void setCheliangSbCode(String cheliangSbCode) {
        this.cheliangSbCode = cheliangSbCode == null ? null : cheliangSbCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.bussins_user_type
     *
     * @return the value of car_mess_detail.bussins_user_type
     *
     * @mbg.generated
     */
    public String getBussinsUserType() {
        return bussinsUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.bussins_user_type
     *
     * @param bussinsUserType the value for car_mess_detail.bussins_user_type
     *
     * @mbg.generated
     */
    public void setBussinsUserType(String bussinsUserType) {
        this.bussinsUserType = bussinsUserType == null ? null : bussinsUserType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.user_mess_name
     *
     * @return the value of car_mess_detail.user_mess_name
     *
     * @mbg.generated
     */
    public String getUserMessName() {
        return userMessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.user_mess_name
     *
     * @param userMessName the value for car_mess_detail.user_mess_name
     *
     * @mbg.generated
     */
    public void setUserMessName(String userMessName) {
        this.userMessName = userMessName == null ? null : userMessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.user_mess_certNo
     *
     * @return the value of car_mess_detail.user_mess_certNo
     *
     * @mbg.generated
     */
    public String getUserMessCertno() {
        return userMessCertno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.user_mess_certNo
     *
     * @param userMessCertno the value for car_mess_detail.user_mess_certNo
     *
     * @mbg.generated
     */
    public void setUserMessCertno(String userMessCertno) {
        this.userMessCertno = userMessCertno == null ? null : userMessCertno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.hyjs_ser_zgz
     *
     * @return the value of car_mess_detail.hyjs_ser_zgz
     *
     * @mbg.generated
     */
    public Integer getHyjsSerZgz() {
        return hyjsSerZgz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.hyjs_ser_zgz
     *
     * @param hyjsSerZgz the value for car_mess_detail.hyjs_ser_zgz
     *
     * @mbg.generated
     */
    public void setHyjsSerZgz(Integer hyjsSerZgz) {
        this.hyjsSerZgz = hyjsSerZgz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.zhengshu_code
     *
     * @return the value of car_mess_detail.zhengshu_code
     *
     * @mbg.generated
     */
    public String getZhengshuCode() {
        return zhengshuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.zhengshu_code
     *
     * @param zhengshuCode the value for car_mess_detail.zhengshu_code
     *
     * @mbg.generated
     */
    public void setZhengshuCode(String zhengshuCode) {
        this.zhengshuCode = zhengshuCode == null ? null : zhengshuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.shifou_jnshebao
     *
     * @return the value of car_mess_detail.shifou_jnshebao
     *
     * @mbg.generated
     */
    public Integer getShifouJnshebao() {
        return shifouJnshebao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.shifou_jnshebao
     *
     * @param shifouJnshebao the value for car_mess_detail.shifou_jnshebao
     *
     * @mbg.generated
     */
    public void setShifouJnshebao(Integer shifouJnshebao) {
        this.shifouJnshebao = shifouJnshebao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.shifou_jnsheb
     *
     * @return the value of car_mess_detail.shifou_jnsheb
     *
     * @mbg.generated
     */
    public Integer getShifouJnsheb() {
        return shifouJnsheb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.shifou_jnsheb
     *
     * @param shifouJnsheb the value for car_mess_detail.shifou_jnsheb
     *
     * @mbg.generated
     */
    public void setShifouJnsheb(Integer shifouJnsheb) {
        this.shifouJnsheb = shifouJnsheb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.shifou_czh
     *
     * @return the value of car_mess_detail.shifou_czh
     *
     * @mbg.generated
     */
    public Integer getShifouCzh() {
        return shifouCzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.shifou_czh
     *
     * @param shifouCzh the value for car_mess_detail.shifou_czh
     *
     * @mbg.generated
     */
    public void setShifouCzh(Integer shifouCzh) {
        this.shifouCzh = shifouCzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_mess_detail.card_no
     *
     * @return the value of car_mess_detail.card_no
     *
     * @mbg.generated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_mess_detail.card_no
     *
     * @param cardNo the value for car_mess_detail.card_no
     *
     * @mbg.generated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }
}