package com.example.springbootdemo.pojo;

import java.util.Date;

public class MakeOnCard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_on_card.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_on_card.phone
     *
     * @mbg.generated
     */
    private String phone;

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getUserName() {
        return userName;
    }

    public String getPhone() {
        return phone;
    }
}