package com.example.springbootdemo.pojo;

public class WechatUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.openId
     *
     * @mbg.generated
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.subscribe
     *
     * @mbg.generated
     */
    private Integer subscribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.subscribeTime
     *
     * @mbg.generated
     */
    private String subscribetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.language
     *
     * @mbg.generated
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.headImgUrl
     *
     * @mbg.generated
     */
    private String headimgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.id
     *
     * @return the value of wechat_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.id
     *
     * @param id the value for wechat_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.openId
     *
     * @return the value of wechat_user.openId
     *
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.openId
     *
     * @param openid the value for wechat_user.openId
     *
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.subscribe
     *
     * @return the value of wechat_user.subscribe
     *
     * @mbg.generated
     */
    public Integer getSubscribe() {
        return subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.subscribe
     *
     * @param subscribe the value for wechat_user.subscribe
     *
     * @mbg.generated
     */
    public void setSubscribe(Integer subscribe) {
        this.subscribe = subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.subscribeTime
     *
     * @return the value of wechat_user.subscribeTime
     *
     * @mbg.generated
     */
    public String getSubscribetime() {
        return subscribetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.subscribeTime
     *
     * @param subscribetime the value for wechat_user.subscribeTime
     *
     * @mbg.generated
     */
    public void setSubscribetime(String subscribetime) {
        this.subscribetime = subscribetime == null ? null : subscribetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.nickname
     *
     * @return the value of wechat_user.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.nickname
     *
     * @param nickname the value for wechat_user.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.sex
     *
     * @return the value of wechat_user.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.sex
     *
     * @param sex the value for wechat_user.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.country
     *
     * @return the value of wechat_user.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.country
     *
     * @param country the value for wechat_user.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.province
     *
     * @return the value of wechat_user.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.province
     *
     * @param province the value for wechat_user.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.city
     *
     * @return the value of wechat_user.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.city
     *
     * @param city the value for wechat_user.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.language
     *
     * @return the value of wechat_user.language
     *
     * @mbg.generated
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.language
     *
     * @param language the value for wechat_user.language
     *
     * @mbg.generated
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.headImgUrl
     *
     * @return the value of wechat_user.headImgUrl
     *
     * @mbg.generated
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.headImgUrl
     *
     * @param headimgurl the value for wechat_user.headImgUrl
     *
     * @mbg.generated
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl == null ? null : headimgurl.trim();
    }
}