package com.example.springbootdemo.dao;

import com.example.springbootdemo.pojo.CarCardDetail;
import com.example.springbootdemo.pojo.CarMessDetail;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;

public interface CarCardDetailMapper {
    /**
     * 获取未预约车牌列表
     */
    List<String> findCardDetail(String wechatId);

    /**
     * 获取用户车牌列表
     */
    Integer cardIsNo(String wechatId);
    /**
     * 添加车牌信息
     */
    int insertCardMess(Map<String,Object> map);
    /**
     * 获取审核通过的车牌信息
     */
    List<CarMessDetail> findCardMess(String wechatId);

    /**
     * 修改车牌状态
     */
    int updateCard(Map<String,Object> map);

    /**
     * 修改个人车牌信息状态
     */
    int updateCardMess(Map<String,Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_card_detail
     *
     * @mbg.generated
     */
    int insert(CarCardDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_card_detail
     *
     * @mbg.generated
     */
    int insertSelective(CarCardDetail record);
}