package com.example.springbootdemo.dao;

import com.example.springbootdemo.pojo.CarMessDetail;

import java.util.List;
import java.util.Map;

public interface CarMessDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_mess_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_mess_detail
     *
     * 录入车牌信息
     */
    int insert(Map<String,Object> map);

    /**
     * 查询个人车牌信息
     */
    List<CarMessDetail> findAll(String wechatid);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_mess_detail
     *
     * @mbg.generated
     */
    int insertSelective(CarMessDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_mess_detail
     *
     * @mbg.generated
     */
    CarMessDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_mess_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CarMessDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_mess_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CarMessDetail record);
}