package com.example.springbootdemo.dao;

import com.example.springbootdemo.pojo.Student;

import java.util.List;
import java.util.Map;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated
     */
    int insertSelective(Student record);

    List<Student> findAllUser();
}