package com.example.springbootdemo.dao;

import java.util.Map;

public interface UserDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * 注册个人信息
     */
    int insertUser(Map<String,Object> record);


}